# Generated by Django 6.0.4 on 2026-04-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=50)),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('ph', models.FloatField()),
                ('soil_type', models.CharField(max_length=50)),
                ('crop_type', models.CharField(max_length=50)),
                ('recommended_fertilizer', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('shap_values', models.JSONField(help_text='Stored SHAP model interpretability values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
